/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MisClases;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ErickYael
 */
public class AltaPedido extends javax.swing.JFrame {
ConexionBD conex;
    /**
     * Creates new form AltaPedido
     */
    public AltaPedido() {
        initComponents();
        setLocationRelativeTo(null);
        btnBuscar.setEnabled(false);
        btnSesion.setEnabled(true);
        btnCancelar.setEnabled(false);
        btnGuardar.setEnabled(false);
        txtClaveProducto.setEnabled(false);
        txtClaveUsuario.setEnabled(true);
        pswContraseña.setEnabled(true);
        txtClaveUsuario.requestFocus();
        listhoras.setEnabled(false);
        listmin.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtClaveUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtClaveProducto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        listhoras = new javax.swing.JComboBox();
        listmin = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pswContraseña = new javax.swing.JPasswordField();
        btnSesion = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblNombreProducto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MisClases/iconos/1486164756-113_79715.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MisClases/iconos/Save-as-icon.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });

        btnCancelar.setForeground(new java.awt.Color(255, 51, 0));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MisClases/iconos/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MisClases/iconos/regresar.png"))); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });

        jLabel1.setText("Clave de usuario");

        txtClaveUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClaveUsuarioKeyTyped(evt);
            }
        });

        jLabel2.setText("Clave del producto");

        txtClaveProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClaveProductoKeyTyped(evt);
            }
        });

        jLabel3.setText("Hora de entrega");

        label1.setText("hrs.");

        listhoras.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "08", "09", "10", "11", "12", "13", "14", "15", "16", "17" }));
        listhoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listhorasActionPerformed(evt);
            }
        });

        listmin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", " ", " ", " ", " " }));

        jLabel4.setText("min.");

        jLabel5.setText("Total a pagar: $");

        lblTotal.setBackground(new java.awt.Color(204, 204, 255));
        lblTotal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setText("Contraseña");

        btnSesion.setForeground(new java.awt.Color(0, 153, 102));
        btnSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MisClases/iconos/sesion.png"))); // NOI18N
        btnSesion.setText("Iniciar sesión");
        btnSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSesionMouseClicked(evt);
            }
        });

        jLabel7.setText("Nombre del producto");

        lblNombreProducto.setBackground(new java.awt.Color(204, 204, 255));
        lblNombreProducto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegresar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtClaveUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(pswContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSesion))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(62, 62, 62)
                                .addComponent(listhoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(listmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombreProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtClaveProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar)
                    .addComponent(btnRegresar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClaveUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(pswContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSesion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtClaveProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNombreProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(listhoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(listmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        label1.getAccessibleContext().setAccessibleName("hrs");
        label1.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
void limpiar(){
        txtClaveUsuario.setText("");
        txtClaveProducto.setText("");
        pswContraseña.setText("");
        pswContraseña.setEnabled(true);
        btnBuscar.setEnabled(false);
        btnSesion.setEnabled(true);
        btnCancelar.setEnabled(false);
        btnGuardar.setEnabled(false);
        txtClaveProducto.setEnabled(false);
        txtClaveUsuario.setEnabled(true);
        txtClaveUsuario.requestFocus();
        listhoras.setEnabled(false);
        listmin.setEnabled(false);
        lblTotal.setText("");
        lblNombreProducto.setText("");
       
}
    
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void listhorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listhorasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listhorasActionPerformed

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        // TODO add your handling code here:
        Menu m= new Menu();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        // TODO add your handling code here:
        conex = new ConexionBD ("lincelunch", "root", "", "jdbc:mysql://localhost/");
        if(conex.getConex()!=null){          
          String cadsql="";
          ResultSet consulta;     
          
            cadsql="select*from productos where(ID_producto='"+txtClaveProducto.getText()+"')";
            try {
                conex.Consulta(cadsql);               
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
                Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
            }
          consulta=conex.getConsulta();
            try {
                if((consulta.next())){
                    txtClaveProducto.setEnabled(false);
                    listhoras.setEnabled(true);
                    listmin.setEnabled(true);
                    btnCancelar.setEnabled(true);
                    btnGuardar.setEnabled(true);                                                                   
                    btnBuscar.setEnabled(false);
                    lblTotal.setText(consulta.getString("Costo"));
                    lblNombreProducto.setText(consulta.getString("Nombrep"));
                } 
                else{
                    
                    
                    JOptionPane.showMessageDialog(this,"El producto con la clave ingresada no existe");
                    this.limpiar();
                }
                
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
                Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
            }
           
        }
        else{
            JOptionPane.showMessageDialog(this, "Error de conexiòn");
        }
                                         
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        // TODO add your handling code here:
        String cadsql="";
        conex=new ConexionBD("lincelunch","root","","jdbc:mysql://localhost/");
        cadsql="insert into pedidos values("+100+txtClaveUsuario.getText()+","+txtClaveUsuario.getText()+","+txtClaveProducto.getText()+","+lblTotal.getText()+","+"'"+listhoras.getSelectedItem()+":"+listmin.getSelectedItem()+":00')";
        if((!"".equals(txtClaveUsuario.getText()))&&(!"".equals(txtClaveProducto.getText()))){
        System.out.println(cadsql);
        
    try {
        conex.EjecutarSentencia(cadsql);
        
        JOptionPane.showMessageDialog(this, "Se han registrado el pedido.");
        conex.CerrarSentencia();
        conex.CerrarConexion();
        this.limpiar();
        
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage());
        JOptionPane.showMessageDialog(this, "Error al almacenar los datos");
        this.limpiar();
        Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
    }
        }
        else{
            JOptionPane.showMessageDialog(this,"Error. Es necesario ingresar una clave para el usuario y el producto");
            this.limpiar();
        }
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void txtClaveUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClaveUsuarioKeyTyped
        // TODO add your handling code here:
        char tecla;
        String num;
        tecla=evt.getKeyChar();
        num=txtClaveUsuario.getText();
        if((tecla<'0')||(tecla>'9')){
            evt.consume();
            if((tecla=='.')){
                evt.consume();
            }
            if(num.contains(".")){
                evt.consume();
            }
            if((tecla==',')){
                evt.consume();
            }
            if(num.contains(",")){
                evt.consume();
            }
                      
        }
    }//GEN-LAST:event_txtClaveUsuarioKeyTyped

    private void txtClaveProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClaveProductoKeyTyped
        // TODO add your handling code here:
        char tecla;
        String num;
        tecla=evt.getKeyChar();
        num=txtClaveProducto.getText();
        if((tecla<'0')||(tecla>'9')){
            evt.consume();
            if((tecla=='.')){
                evt.consume();
            }
            if(num.contains(".")){
                evt.consume();
            }
            if((tecla==',')){
                evt.consume();
            }
            if(num.contains(",")){
                evt.consume();
            }
                      
        }
    }//GEN-LAST:event_txtClaveProductoKeyTyped

    private void btnSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSesionMouseClicked
        // TODO add your handling code here:
        conex = new ConexionBD ("lincelunch", "root", "", "jdbc:mysql://localhost/");
        if(conex.getConex()!=null){          
          String cadsql="";
          ResultSet consulta;     
          cadsql="select*from altausuario where(ID_usuario='"+txtClaveUsuario.getText()+"')";
            try {
                conex.Consulta(cadsql);               
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
                Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
            }
          consulta=conex.getConsulta();
            try {
                if((consulta.next())){
                    txtClaveUsuario.setEnabled(false);
                    pswContraseña.setEnabled(false);
                    txtClaveProducto.setEnabled(true);
                    btnCancelar.setEnabled(false);
                    btnGuardar.setEnabled(false);                                                                   
                    btnBuscar.setEnabled(true);
                    btnSesion.setEnabled(false);
                } 
                else{
                    
                    
                    JOptionPane.showMessageDialog(this,"El usuario con la clave ingresada no existe");
                    this.limpiar();
                }
                
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
                Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
            }
            cadsql="select*from altausuario where(Contraseña='"+pswContraseña.getText()+"')";
            try {
                conex.Consulta(cadsql);               
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
                Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
            }
          consulta=conex.getConsulta();
            try {
                if((consulta.next())){
                    txtClaveUsuario.setEnabled(false);
                    pswContraseña.setEnabled(false);
                    txtClaveProducto.setEnabled(true);
                    listhoras.setEnabled(true);
                    listmin.setEnabled(true);
                    btnCancelar.setEnabled(false);
                    btnGuardar.setEnabled(false);                                                                   
                    btnBuscar.setEnabled(true);
                    btnSesion.setEnabled(false);
                    
                } 
                else{
                    
                    
                    JOptionPane.showMessageDialog(this,"La contraseña es incorrecta");
                    this.limpiar();
                }
                
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
                Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
            }
           
        }
        else{
            JOptionPane.showMessageDialog(this, "Error de conexiòn");
        }
    }//GEN-LAST:event_btnSesionMouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        // TODO add your handling code here:
        this.limpiar();
    }//GEN-LAST:event_btnCancelarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private javax.swing.JLabel lblNombreProducto;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JComboBox listhoras;
    private javax.swing.JComboBox listmin;
    private javax.swing.JPasswordField pswContraseña;
    private javax.swing.JTextField txtClaveProducto;
    private javax.swing.JTextField txtClaveUsuario;
    // End of variables declaration//GEN-END:variables
}
